-- bookid�Լ�
CREATE SEQUENCE hzs_book_id_seq START WITH 1 INCREMENT BY 1;
ALTER TABLE hzs_book ALTER COLUMN book_id SET DEFAULT nextval('hzs_book_id_seq');

-- book_copy copy_id�Լ�
CREATE SEQUENCE hzs_book_copy_id_seq START WITH 1 INCREMENT BY 1;
ALTER TABLE hzs_book_copy ALTER COLUMN copy_id SET DEFAULT nextval('hzs_book_copy_id_seq');

-- rental_id�Լ�
CREATE SEQUENCE hzs_rental_id_seq START WITH 1 INCREMENT BY 1;
ALTER TABLE hzs_rental ALTER COLUMN rental_id SET DEFAULT nextval('hzs_rental_id_seq');


-- customer_id�Լ�
CREATE SEQUENCE hzs_customer_id_seq START WITH 1 INCREMENT BY 1;
ALTER TABLE hzs_customer ALTER COLUMN customer_id SET DEFAULT nextval('hzs_customer_id_seq');


-- ����constraints

ALTER TABLE HZS_CUSTOMER
ADD CONSTRAINT CK_CUSTOMER_ID_TYPE
CHECK (ID_TYPE IN ('Passport', 'SSN', 'Driver_License'));



ALTER TABLE HZS_SPONSOR
ADD CONSTRAINT CK_SPONSOR_TYPE
CHECK (SPONSOR_TYPE IN ('INDIVIDUAL', 'ORGANIZATION'));

ALTER TABLE HZS_RENTAL
ADD CONSTRAINT CK_RENTAL_DATES
CHECK (
    ACTUAL_RETURN_DATE IS NULL
    OR ACTUAL_RETURN_DATE >= BORROW_DATE
);

ALTER TABLE HZS_PAYMENT
ADD CONSTRAINT CK_PAYMENT_METHOD
CHECK (METHOD IN ('CASH', 'CREDIT', 'DEBIT', 'PAYPAL'));

ALTER TABLE HZS_INVOICE
ADD CONSTRAINT CK_INVOICE_AMOUNT
CHECK (INVOIC__AMOUNT >= 0);

ALTER TABLE HZS_EXHIBITION
ADD CONSTRAINT CK_EXHIBITION_EXPENSE
CHECK (EXPENSE >= 0);

ALTER TABLE HZS_BOOK_COPY 
ADD CONSTRAINT C_STATUS_TYPE 
CHECK(STATUS IN ('AVAILABLE', 'UNAVAILABLE'));

ALTER TABLE HZS_RENTAL 
ADD CONSTRAINT C_RENTAL_STATUS 
CHECK (RENTAL_STATUS IN ('BORROWED', 'RETURNED', 'LATE'));

ALTER TABLE HZS_SEMINAR_SPONSOR 
ADD CONSTRAINT C_SPONSORED_AMOUNT 
CHECK (AMOUNT >= 0);

ALTER TABLE HZS_STUDY_ROOM 
ADD CONSTRAINT C_POSITIVE_CAPACITY 
CHECK (CAPACITY > 0);
