
-- SELECT tgname, tgrelid::regclass AS table_name, tgfoid::regprocedure AS function_name
-- FROM pg_trigger
-- WHERE tgname LIKE 'ARC_FKArc_%';



INSERT INTO HZS_SPONSOR VALUES (12, 'O')
;

INSERT INTO HZS_ORGANIZATION VALUES (12, 'Art & Design Foundation')
;

INSERT INTO HZS_SPONSOR VALUES (10, 'I')
;

INSERT INTO HZS_INDIVIDUAL VALUES (10, 'Liam', 'Hassan')
;

INSERT INTO HZS_CUSTOMER (CUSTOMER_ID, L_NAME, F_NAME, PHONE, EMAIL, ID_TYPE, ID_NUM) VALUES 
(5, 'Patel', 'Raj', '5554447788', 'raj.patel@example.com', 'SSN', '987-65-4321')
;

INSERT INTO HZS_CUSTOMER (CUSTOMER_ID, L_NAME, F_NAME, PHONE, EMAIL, ID_TYPE, ID_NUM) VALUES 
(1, 'Smith', 'John', '5551234567', 'john.smith@example.com', 'PASSPORT', 'P1234567')
;

INSERT INTO HZS_EVENT (EVENT_ID, E_NAME, EVENT_TYPE, START_DATETIME, STOP_DATETIME, TOPIC) VALUES 
(110, 'Visual Arts Exhibition', 'E', DATE '2025-05-28', DATE '2025-05-30', 'Arts')
;




INSERT INTO HZS_EXHIBITION (EVENT_ID, EXPENSE) VALUES 
(110, 600.00)
;

INSERT INTO HZS_EXHIBITION_ACCESS (REGISTRATION_ID, CUSTOMER_ID, EVENT_ID) VALUES 
(5, 5, 110)
;


INSERT INTO HZS_AUTHOR (AUTHOR_ID, F_NAME, L_NAME, EMAIL, COUNTRY, STATE, STREET, CITY) VALUES 
(1, 'Alice', 'Walker', 'alice.walker@example.com', 'USA', 'MA', '123 Elm Street', 'Boston')
;


INSERT INTO HZS_BOOK (BOOK_ID, B_NAME, TOPIC) VALUES 
(1001, 'Exploring Space: A Journey Beyond Earth', 'Science')
;


INSERT INTO HZS_BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (1001, 1)
;


INSERT INTO HZS_BOOK_COPY (COPY_ID, STATUS, BOOK_ID) VALUES (1, 'AVAILABLE', 1001)
;


INSERT INTO HZS_RENTAL (RENTAL_ID, RENTAL_STATUS, BORROW_DATE, EXPECTED_RETURN_DATE, ACTUAL_RETURN_DATE, CUSTOMER_ID, COPY_ID) 
VALUES (1, 'RETURNED', DATE '2025-03-01', DATE '2025-03-05', DATE '2025-03-05', 1, 1)
;


INSERT INTO HZS_PAYMENT (PAYMENT_ID, PAYMENT_DATE, METHOD, CARD_HOLDER_L_NAME, CARD_HOLDER_F_NAME, AMOUNT, INVOICE_ID) 
VALUES (1, DATE '2025-03-06', 'CREDIT', 'Smith', 'John', 0.8, 1)
;

INSERT INTO HZS_SPONSOR VALUES (5, 'I')
;


INSERT INTO HZS_EVENT (EVENT_ID, E_NAME, EVENT_TYPE, START_DATETIME, STOP_DATETIME, TOPIC) VALUES 
(109, 'Historical Figures Seminar', 'S', DATE '2025-05-25', DATE '2025-05-25', 'History')
;

INSERT INTO HZS_SEMINAR (EVENT_ID, DESCRIP) VALUES 
(109, 'OPQ')
;

INSERT INTO HZS_SEMINAR_SPONSOR (SPONSOR_ID, EVENT_ID, AMOUNT) VALUES (5, 109, 130.00)
;

INSERT INTO HZS_SEMINAR_ACCESS (INVITATION_ID, AUTHOR_ID, EVENT_ID) 
VALUES ('INV12345', 1, 109)
;

INSERT INTO HZS_STUDY_ROOM (ROOM_ID, CAPACITY) VALUES (1, 4)
;

INSERT INTO HZS_ROOM_RESERVATION (RESERVATION_ID, TOPIC_DESCRIPTION, RESERVE_DATE, START_TIME, END_TIME, GROUP_SIZE, CUSTOMER_ID, ROOM_ID, L_NAME, F_NAME) 
VALUES (1, 'AI Project Discussion', DATE '2025-04-01', TO_DATE('10:00', 'HH24:MI'), TO_DATE('12:00', 'HH24:MI'), 4, 1, 1, 'Smith', 'John')
;